import type { BrandAIAnalysis, BrandIntelItem, BrandIntelSummary, RegionIntel } from './api/client'

export const MOCK_BRANDS: BrandIntelItem[] = [
  {
    brand_id: 'luckin',
    brand_name: '瑞幸咖啡',
    stock_name: 'Luckin Coffee',
    stock_code: 'LKNCY',
    category: '咖啡',
    headquarters: '厦门',
    listed_status: '美股粉单市场',
    key_cities: ['上海', '北京', '杭州', '广州', '成都'],
    store_count: 20500,
    price_band: '12-28 元',
    sentiment_level: '偏正面',
    investment_risk_score: 37.62,
    franchise_risk_score: 41.8,
    risk_level: '中低风险',
    growth_signal: '门店规模领先，数字化运营能力强，适合持续跟踪行业景气度和单店效率。',
    market_signal: '核心城市竞争激烈，但品牌认知度和价格带优势明显。',
    franchise_signal: '联营与合作模式较成熟，加盟前仍需核实区域保护、选址和成本回收周期。',
    risk_tags: ['高速扩张', '价格竞争', '咖啡刚需化'],
    metrics: [
      { label: '近端热度', value: '86', hint: 'NEWS + STORE' },
      { label: '舆情倾向', value: '偏正面', hint: 'PUBLIC SENTIMENT' },
      { label: '加盟关注', value: '较高', hint: 'FRANCHISE' },
    ],
  },
  {
    brand_id: 'mixue',
    brand_name: '蜜雪冰城',
    stock_name: '蜜雪集团',
    stock_code: '02097.HK',
    category: '茶饮',
    headquarters: '郑州',
    listed_status: '港股上市',
    key_cities: ['郑州', '广州', '成都', '武汉', '杭州'],
    store_count: 36000,
    price_band: '4-12 元',
    sentiment_level: '中性偏正面',
    investment_risk_score: 45.2,
    franchise_risk_score: 52.6,
    risk_level: '中风险',
    growth_signal: '下沉市场覆盖强，供应链规模优势明显，需关注门店密度和同质化竞争。',
    market_signal: '低价茶饮需求稳定，但区域饱和度上升。',
    franchise_signal: '加盟体系成熟，风险主要来自商圈重叠、利润空间和门店密度。',
    risk_tags: ['门店密度高', '低价竞争', '供应链优势'],
    metrics: [
      { label: '近端热度', value: '91', hint: 'NEWS + STORE' },
      { label: '舆情倾向', value: '中性', hint: 'PUBLIC SENTIMENT' },
      { label: '加盟关注', value: '高', hint: 'FRANCHISE' },
    ],
  },
  {
    brand_id: 'chagee',
    brand_name: '霸王茶姬',
    stock_name: 'CHAGEE',
    stock_code: 'CHA',
    category: '茶饮',
    headquarters: '昆明',
    listed_status: '美股上市',
    key_cities: ['上海', '杭州', '成都', '深圳', '广州'],
    store_count: 6400,
    price_band: '15-28 元',
    sentiment_level: '高热度',
    investment_risk_score: 51.8,
    franchise_risk_score: 48.7,
    risk_level: '中风险',
    growth_signal: '品牌增长快，东方茶饮定位清晰，需关注上市后业绩兑现和舆情波动。',
    market_signal: '新中式茶饮热度高，核心商圈竞争同步加剧。',
    franchise_signal: '扩张速度快，加盟前要重点核实城市容量、选址质量和品牌政策。',
    risk_tags: ['高速增长', '舆情敏感', '新中式茶饮'],
    metrics: [
      { label: '近端热度', value: '94', hint: 'NEWS + STORE' },
      { label: '舆情倾向', value: '高热度', hint: 'PUBLIC SENTIMENT' },
      { label: '加盟关注', value: '较高', hint: 'FRANCHISE' },
    ],
  },
]

export const MOCK_SUMMARY: BrandIntelSummary = {
  brand_count: 6,
  listed_brand_count: 4,
  city_count: 9,
  news_count: 186,
  average_investment_risk: 49.19,
  average_franchise_risk: 50.3,
  risk_distribution: {
    中低风险: 2,
    中风险: 2,
    较高风险: 2,
  },
  top_attention_brands: MOCK_BRANDS,
}

export const MOCK_REGION: RegionIntel = {
  city: '杭州',
  market_heat: '高活跃',
  competition_level: '高竞争',
  consumer_profile: '年轻客群和互联网办公场景集中，咖啡与新茶饮接受度高。',
  store_density_index: 81.2,
  franchise_risk_score: 52.7,
  key_competitors: ['瑞幸咖啡', '库迪咖啡', '星巴克', '霸王茶姬'],
  brand_cards: [
    { brand_name: '瑞幸咖啡', store_count: 860, competition_pressure: '高', franchise_fit: '关注点位差异' },
    { brand_name: '库迪咖啡', store_count: 610, competition_pressure: '中高', franchise_fit: '谨慎测算回本' },
    { brand_name: '霸王茶姬', store_count: 330, competition_pressure: '中', franchise_fit: '可关注新兴商圈' },
  ],
  opportunity_points: ['年轻消费力强', '办公楼与社区复合场景多', '数字化运营适配度高'],
  risk_points: ['咖啡价格战明显', '热门商圈门店拥挤', '品牌重叠度高'],
  follow_up_data: ['商圈客流分时段数据', '竞品活动频率', '外卖平台销量', '加盟费用明细'],
}

export const MOCK_AI_ANALYSIS: BrandAIAnalysis = {
  source: 'local_rules',
  summary: '瑞幸咖啡适合从投资风险和加盟风险两个角度综合观察。该品牌属于咖啡，当前风险等级为中低风险，系统本次仅基于后端聚合摘要生成解释。',
  investment_view: '当前投资风险指数为 37.62，品牌规模和数字化能力较强，但仍需要跟踪行情波动、财报和行业价格竞争。',
  franchise_view: '在杭州场景下，地区加盟风险指数为 52.70，市场热度较高，加盟前应重点核实商圈租金、竞品密度和区域保护政策。',
  risk_points: ['高速扩张', '价格竞争', '核心商圈租金高', '同类品牌密度高'],
  action_suggestions: ['股民侧重点跟踪行情、财报和负面新闻。', '加盟侧重点比较门店密度、租金成本和竞品数量。'],
  follow_up_data: ['近 30 至 90 天行情数据', '近 10 条品牌新闻', '目标城市门店与竞品数量', '加盟费用和回本周期'],
  token_saving_note: '本接口采用手动触发，只向模型传递品牌摘要、地区摘要和评分结果；列表切换不会自动调用 DeepSeek。',
}
